const fs = require('fs');
const path = require('path');
const vm = require('vm');
const assert = require('assert');

const context = { window: {}, console };
vm.createContext(context);
const base = fs.readFileSync(path.join(__dirname, '..', 'web', 'excel_secure_query.js'), 'utf8');
const aggregation = fs.readFileSync(path.join(__dirname, '..', 'web', 'excel_secure_aggregation.js'), 'utf8');
vm.runInContext(base, context);
vm.runInContext(aggregation, context);

async function execute(rows, query) {
  return JSON.parse(await context.window.executeSecureExcelQuery(JSON.stringify({ rows, query })));
}
function clone(rows) { return JSON.parse(JSON.stringify(rows)); }

async function run() {
  const revenueData = [
    ['City', 'Revenue Generated'],
    ['Delhi', '1000'], ['Delhi', 2000], ['Mumbai', '3000'], ['Mumbai', 'bad'], ['Kolkata', ''],
  ];
  const revenueOriginal = clone(revenueData);
  const revenue = await execute(revenueData, 'What is the total revenue generated by each city?');
  assert.strictEqual(revenue.success, true);
  assert.strictEqual(revenue.operation.measure, 'Revenue Generated');
  assert.deepStrictEqual(clone(revenue.operation.rows), [
    { City: 'Mumbai', sum: 3000 }, { City: 'Delhi', sum: 3000 },
  ]);
  assert.deepStrictEqual(revenueData, revenueOriginal);

  const salesData = [['City', 'Sales Amount'], ['Delhi', 100], ['Delhi', '200'], ['Mumbai', 50]];
  const sales = await execute(salesData, 'What is the total sales amount by city?');
  assert.strictEqual(sales.success, true);
  assert.strictEqual(sales.operation.measure, 'Sales Amount');
  assert.deepStrictEqual(clone(sales.operation.rows), [{ City: 'Delhi', sum: 300 }, { City: 'Mumbai', sum: 50 }]);

  const derivedData = [['City', 'Quantity', 'Unit Selling Price'], ['Delhi', 2, 100], ['Delhi', '3', '50'], ['Mumbai', 4, 20]];
  const derivedOriginal = clone(derivedData);
  const derived = await execute(derivedData, 'What is the total revenue generated by each city?');
  assert.strictEqual(derived.success, true);
  assert.strictEqual(derived.diagnostics.revenue_resolution, 'derived');
  assert.deepStrictEqual(clone(derived.operation.rows), [{ City: 'Delhi', sum: 350 }, { City: 'Mumbai', sum: 80 }]);
  assert.deepStrictEqual(derivedData, derivedOriginal);

  const priceOnly = [['City', 'Price Range', 'Aggregate rating', 'Votes'], ['Delhi', '100-200', 4.5, 10], ['Mumbai', '200-300', 4.0, 20]];
  const unavailable = await execute(priceOnly, 'What is the total revenue generated by each city?');
  assert.strictEqual(unavailable.success, false);
  assert.match(unavailable.error, /Revenue cannot be calculated from this worksheet/i);
  assert.strictEqual(unavailable.diagnostics.derived_revenue, false);

  const salePriceOnly = [['City', 'Sale Price', 'Aggregate rating', 'Votes'], ['Delhi', 100, 4.5, 10], ['Mumbai', 200, 4.0, 20]];
  const noPriceFallback = await execute(salePriceOnly, 'What is the total sales by city?');
  assert.strictEqual(noPriceFallback.success, false);
  assert.match(noPriceFallback.error, /Revenue cannot be calculated from this worksheet/i);

  const ambiguous = [['City', 'Revenue', 'Total Revenue'], ['Delhi', 100, 110], ['Mumbai', 200, 210]];
  const ambiguousResult = await execute(ambiguous, 'What is the total revenue by city?');
  assert.strictEqual(ambiguousResult.success, false);
  assert.match(ambiguousResult.error, /ambiguous/i);

  const transactionAmbiguous = [['City', 'Quantity', 'Quantity Sold', 'Unit Price'], ['Delhi', 2, 2, 100]];
  const transactionResult = await execute(transactionAmbiguous, 'What is the total revenue by city?');
  assert.strictEqual(transactionResult.success, false);
  assert.match(transactionResult.error, /Revenue cannot be calculated|ambiguous/i);

  const blankNumeric = [['City', 'Revenue'], ['Delhi', '100'], ['Delhi', 'bad'], ['Mumbai', ''], ['Mumbai', 200]];
  const missing = await execute(blankNumeric, 'What is the total revenue by city?');
  assert.strictEqual(missing.success, true);
  assert.deepStrictEqual(clone(missing.operation.rows), [{ City: 'Mumbai', sum: 200 }, { City: 'Delhi', sum: 100 }]);

  const rating = await execute([
    ['City', 'Aggregate rating'], ['Delhi', 4.5], ['Delhi', 3.5], ['Mumbai', 4.0], ['Mumbai', 'bad'],
  ], 'Which city has the highest average restaurant rating?');
  assert.strictEqual(rating.success, true);
  assert.deepStrictEqual(clone(rating.operation.rows), [{ City: 'Delhi', average: 4 }]);

  const count = await execute([['City', 'Restaurant ID'], ['Delhi', 1], ['Delhi', 2], ['Mumbai', 3]], 'Show the number of restaurants in each city');
  assert.strictEqual(count.success, true);
  assert.strictEqual(count.operation.action, 'group');

  assert.ok(!aggregation.includes('fetch('));
  assert.ok(!aggregation.includes('XMLHttpRequest'));
  console.log('excel_secure_revenue_test.js: all assertions passed');
}
run().catch(error => { console.error(error); process.exitCode = 1; });
