const fs = require('fs');
const path = require('path');
const vm = require('vm');
const assert = require('assert');

const context = { window: {}, console };
vm.createContext(context);
const base = fs.readFileSync(path.join(__dirname, '..', 'web', 'excel_secure_query.js'), 'utf8');
const aggregation = fs.readFileSync(path.join(__dirname, '..', 'web', 'excel_secure_aggregation.js'), 'utf8');
vm.runInContext(base, context);
vm.runInContext(aggregation, context);

async function execute(rows, query) {
  return JSON.parse(await context.window.executeSecureExcelQuery(JSON.stringify({ rows, query })));
}
function clone(rows) { return JSON.parse(JSON.stringify(rows)); }

async function run() {
  const source = [
    ['Restaurant ID', 'City', 'Aggregate rating', 'Region', 'Category', 'Price'],
    [1, 'Delhi', 4.5, 'North', 'A', '10'], [2, 'Delhi', 3.5, 'North', 'A', 20],
    [3, 'Mumbai', 4.0, 'West', 'B', 30], [4, 'Mumbai', '', 'West', 'B', 40],
    [5, '', 5.0, 'East', 'A', 50], [6, null, '5', 'East', 'C', 60], [7, 'Kolkata', 4.5, 'East', 'C', '70'],
  ];
  const original = clone(source);

  const highest = await execute(source, 'Which city has the highest average restaurant rating?');
  assert.strictEqual(highest.success, true); assert.deepStrictEqual(clone(highest.operation.rows), [{ City: 'Kolkata', average: 4.5 }]);
  assert.strictEqual(highest.operation.measure, 'Aggregate rating');
  const average = await execute(source, 'What is the average rating by city?');
  assert.deepStrictEqual(clone(average.operation.rows), [{ City: null, average: 5 }, { City: 'Kolkata', average: 4.5 }, { City: 'Delhi', average: 4 }, { City: 'Mumbai', average: 4 }]);
  const top = await execute(source, 'Show the top 5 cities by average rating.');
  assert.deepStrictEqual(clone(top.operation.rows), [{ City: 'Kolkata', average: 4.5 }, { City: 'Delhi', average: 4 }, { City: 'Mumbai', average: 4 }]);
  const lowest = await execute(source, 'Which city has the lowest average rating?');
  assert.deepStrictEqual(clone(lowest.operation.rows), [{ City: 'Delhi', average: 4 }, { City: 'Mumbai', average: 4 }]);

  const count = await execute(source, 'Show the number of restaurants in each city');
  assert.strictEqual(count.success, true); assert.strictEqual(count.operation.action, 'group');
  const quality = await execute(source, 'Check for missing values and duplicate restaurant IDs');
  assert.strictEqual(quality.success, true); assert.strictEqual(quality.operation.action, 'quality_check');

  const priceOnly = [['City', 'Price Range', 'Aggregate rating', 'Votes'], ['Delhi', '100-200', 4.5, 20], ['Mumbai', '200-300', 4.1, 40]];
  const unavailable = await execute(priceOnly, 'What is the total revenue generated by each city?');
  assert.strictEqual(unavailable.success, false); assert.match(unavailable.error, /Revenue cannot be calculated from this worksheet/i);
  assert.strictEqual(unavailable.diagnostics.derived_revenue, false);

  assert.deepStrictEqual(source, original);
  assert.ok(!aggregation.includes('fetch(')); assert.ok(!aggregation.includes('XMLHttpRequest'));
  console.log('excel_secure_aggregation_test.js: all assertions passed');
}
run().catch(error => { console.error(error); process.exitCode = 1; });
