const fs = require('fs');
const path = require('path');
const vm = require('vm');
const assert = require('assert');

const context = { window: {}, console };
vm.createContext(context);
const base = fs.readFileSync(path.join(__dirname, '..', 'web', 'excel_secure_query.js'), 'utf8');
const aggregation = fs.readFileSync(path.join(__dirname, '..', 'web', 'excel_secure_aggregation.js'), 'utf8');
vm.runInContext(base, context);
vm.runInContext(aggregation, context);

async function execute(rows, query) {
  return JSON.parse(await context.window.executeSecureExcelQuery(JSON.stringify({ rows, query })));
}
function clone(rows) { return JSON.parse(JSON.stringify(rows)); }

async function run() {
  const source = [
    ['Restaurant ID', 'City', 'Aggregate rating', 'Revenue Generated', 'Sales Amount', 'Region', 'Category', 'Price'],
    [1, 'Delhi', 4.5, '1000', '100', 'North', 'A', '10'],
    [2, 'Delhi', 3.5, 2000, 200, 'North', 'A', 20],
    [3, 'Mumbai', 4.0, '3000', '300', 'West', 'B', 30],
    [4, 'Mumbai', '', 1000, 100, 'West', 'B', 40],
    [5, '', 5.0, '4000', '400', 'East', 'A', 50],
    [6, null, '5', 'bad', 'bad', 'East', 'C', 60],
    [7, 'Kolkata', 4.5, 500, 50, 'East', 'C', '70'],
  ];
  const original = clone(source);

  const revenue = await execute(source, 'What is the total revenue generated by each city?');
  assert.strictEqual(revenue.success, true);
  assert.strictEqual(revenue.operation.action, 'aggregate');
  assert.strictEqual(revenue.operation.measure, 'Revenue Generated');
  assert.deepStrictEqual(clone(revenue.operation.rows), [
    { City: 'Mumbai', sum: 4000 }, { City: null, sum: 4000 },
    { City: 'Delhi', sum: 3000 }, { City: 'Kolkata', sum: 500 },
  ]);
  assert.strictEqual(revenue.diagnostics.resolved_measure_column, 'Revenue Generated');

  const sales = await execute(source, 'What is the total sales amount by region?');
  assert.strictEqual(sales.success, true);
  assert.strictEqual(sales.operation.measure, 'Sales Amount');
  assert.deepStrictEqual(clone(sales.operation.rows), [
    { Region: 'East', sum: 450 }, { Region: 'West', sum: 400 }, { Region: 'North', sum: 300 },
  ]);

  const salesPhrase = await execute(source, 'What is the total sales by region?');
  assert.strictEqual(salesPhrase.success, true, 'Sales intent should prefer the sales semantic family over revenue.');
  assert.strictEqual(salesPhrase.operation.measure, 'Sales Amount');
  assert.deepStrictEqual(clone(salesPhrase.operation.rows), [
    { Region: 'East', sum: 450 }, { Region: 'West', sum: 400 }, { Region: 'North', sum: 300 },
  ]);

  const missingNumeric = await execute([
    ['City', 'Revenue'], ['Delhi', '100'], ['Delhi', 'bad'], ['Mumbai', ''], ['Mumbai', 200], ['Kolkata', null],
  ], 'What is the total revenue by city?');
  assert.strictEqual(missingNumeric.success, true);
  assert.deepStrictEqual(clone(missingNumeric.operation.rows), [
    { City: 'Mumbai', sum: 200 }, { City: 'Delhi', sum: 100 },
  ]);

  const derivedSource = [
    ['City', 'Quantity', 'Unit Price'],
    ['Delhi', 2, 100], ['Delhi', '3', '50'], ['Mumbai', 4, 20], ['Mumbai', '', 99], ['Kolkata', 5, 'bad'],
  ];
  const derivedOriginal = clone(derivedSource);
  const derived = await execute(derivedSource, 'What is the total revenue generated by each city?');
  assert.strictEqual(derived.success, true);
  assert.strictEqual(derived.diagnostics.revenue_resolution, 'derived');
  assert.strictEqual(derived.operation.derived_measure, 'quantity * unit price');
  assert.deepStrictEqual(clone(derived.operation.rows), [
    { City: 'Delhi', sum: 350 }, { City: 'Mumbai', sum: 80 },
  ]);
  assert.deepStrictEqual(derivedSource, derivedOriginal);

  const priceRangeOnly = await execute([
    ['City', 'Price Range', 'Aggregate rating', 'Votes'],
    ['Delhi', '100-200', 4.5, 20], ['Mumbai', '200-300', 4.1, 40],
  ], 'What is the total revenue generated by each city?');
  assert.strictEqual(priceRangeOnly.success, false);
  assert.match(priceRangeOnly.error, /Revenue cannot be calculated from this worksheet/i);
  assert.strictEqual(priceRangeOnly.diagnostics.derived_revenue, false);

  const unrelatedNumbers = await execute([
    ['City', 'Aggregate rating', 'Votes', 'Price Range'],
    ['Delhi', 4.5, 100, '100-200'], ['Mumbai', 4.0, 200, '200-300'],
  ], 'What is the total sales by city?');
  assert.strictEqual(unrelatedNumbers.success, false);
  assert.match(unrelatedNumbers.error, /Revenue cannot be calculated from this worksheet|Could not resolve measurement/i);

  const ambiguousRevenue = await execute([
    ['City', 'Revenue', 'Total Revenue', 'Rating'],
    ['Delhi', 100, 110, 4.5], ['Mumbai', 200, 210, 4.0],
  ], 'What is the total revenue by city?');
  assert.strictEqual(ambiguousRevenue.success, false);
  assert.match(ambiguousRevenue.error, /ambiguous/i);
  assert.strictEqual(ambiguousRevenue.diagnostics.measure_resolution, 'ambiguous');

  const highest = await execute(source, 'Which city has the highest average restaurant rating?');
  assert.strictEqual(highest.success, true);
  assert.deepStrictEqual(clone(highest.operation.rows), [{ City: 'Kolkata', average: 4.5 }]);
  assert.strictEqual(highest.operation.measure, 'Aggregate rating');

  const average = await execute(source, 'What is the average rating by city?');
  assert.deepStrictEqual(clone(average.operation.rows), [
    { City: null, average: 5 }, { City: 'Kolkata', average: 4.5 },
    { City: 'Delhi', average: 4 }, { City: 'Mumbai', average: 4 },
  ]);

  const top = await execute(source, 'Show the top 5 cities by average rating.');
  assert.deepStrictEqual(clone(top.operation.rows), [
    { City: 'Kolkata', average: 4.5 }, { City: 'Delhi', average: 4 }, { City: 'Mumbai', average: 4 },
  ]);

  const lowest = await execute(source, 'Which city has the lowest average rating?');
  assert.deepStrictEqual(clone(lowest.operation.rows), [
    { City: 'Delhi', average: 4 }, { City: 'Mumbai', average: 4 },
  ]);

  const count = await execute(source, 'Show the number of restaurants in each city');
  assert.strictEqual(count.success, true);
  assert.strictEqual(count.operation.action, 'group');

  const quality = await execute(source, 'Check for missing values and duplicate restaurant IDs');
  assert.strictEqual(quality.success, true);
  assert.strictEqual(quality.operation.action, 'quality_check');

  assert.deepStrictEqual(source, original);
  assert.ok(!aggregation.includes('fetch('));
  assert.ok(!aggregation.includes('XMLHttpRequest'));
  console.log('excel_secure_aggregation_test.js: all assertions passed');
}
run().catch(error => { console.error(error); process.exitCode = 1; });
