// Generic deterministic worksheet schema intelligence. Only headers are inspected.
(function(){
function normalize(v){return String(v??'').normalize('NFKC').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
function singular(v){let s=normalize(v);if(s.endsWith('ies')&&s.length>3)return s.slice(0,-3)+'y';if(s.endsWith('es')&&/(ches|shes|xes|zes|sses)$/.test(s))return s.slice(0,-2);if(s.endsWith('s')&&!s.endsWith('ss')&&s.length>2)return s.slice(0,-1);return s}
function compact(v){return normalize(v).replace(/ /g,'')}
const roles={city:['city','city name','town','municipality','locality'],region:['region','region name','state','state name','province','area'],country:['country','country name','nation'],cuisine:['cuisine','cuisine type','food cuisine'],category:['category','category name','type','class','classification'],product:['product','product name','item','item name','product description'],restaurant_name:['restaurant','restaurant name','restaurant title','merchant name','business name','outlet name'],restaurant_id:['restaurant id','restaurant identifier','restaurant code','restaurantid','restaurant_id'],identifier:['id','identifier','code','key'],cost:['cost','total cost','unit cost','amount','expense','expenses'],revenue:['revenue','total revenue','revenue amount','revenue generated','generated revenue','gross revenue','net revenue'],sales:['sales','total sales','sales amount','sale amount','total sales amount','sales revenue','sales generated'],quantity:['quantity','qty','quantity sold','units sold','units','number sold'],price:['price','unit price','sale price','selling price','selling unit price','price per unit'],rating:['rating','average rating','aggregate rating','score','rating score'],date:['date','datetime','date time','timestamp','time']};
function info(headers){return headers.map((h,i)=>({i,name:String(h??'').trim(),n:normalize(h)})).filter(x=>x.name)}
function resolve(headers,requested,options={}){const wanted=normalize(requested),ws=singular(wanted),list=info(headers),role=options.role||null;if(!wanted)return{index:-1,requested:'',candidates:[]};let hits=list.filter(x=>x.n===wanted||compact(x.n)===compact(wanted));if(hits.length===1){console.log('[LOCAL RESOLVER] schema.resolve stage=exact match='+list[hits[0].i].name);return{index:hits[0].i,requested,candidates:hits,method:'exact'};}if(hits.length>1){console.log('[LOCAL RESOLVER] schema.resolve stage=exact match=ambiguous');return{index:-1,requested,candidates:hits,method:'ambiguous'};}hits=list.filter(x=>x.n===ws||singular(x.n)===ws);if(hits.length===1)return{index:hits[0].i,requested,candidates:hits,method:'inflection'};if(hits.length>1)return{index:-1,requested,candidates:hits,method:'ambiguous'};const requestedRole=Object.keys(roles).find(r=>r===ws||roles[r].includes(wanted)||roles[r].includes(ws));if(wanted!==ws&&requestedRole&&(!role||role===requestedRole||(role==='dimension'&&['city','region','country','cuisine','category','product','restaurant_name'].includes(requestedRole)))){const semanticHits=list.filter(x=>roles[requestedRole].includes(x.n));if(semanticHits.length===1)return{index:semanticHits[0].i,requested,candidates:semanticHits,method:'semantic'};if(semanticHits.length>1)return{index:-1,requested,candidates:semanticHits,method:'ambiguous'}}if(role&&roles[role]){hits=list.filter(x=>roles[role].includes(x.n));if(hits.length===1)return{index:hits[0].i,requested,candidates:hits,method:'semantic'};if(hits.length>1)return{index:-1,requested,candidates:hits,method:'ambiguous'}}const stop=new Set(['the','a','an','of','by','per','each','with','for','to','from','top','bottom','total','sum','average','avg','mean','count']);const tokens=ws.split(' ').filter(t=>t.length>1&&!stop.has(t));if(tokens.length){const scored=list.map(x=>{const xt=x.n.split(' '),score=tokens.reduce((s,t)=>s+(xt.includes(t)?3:(x.n.includes(t)?1:0)),0);return{...x,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);if(scored.length===1||(scored.length>1&&scored[0].score>scored[1].score))return{index:scored[0].i,requested,candidates:[scored[0]],method:'token'};if(scored.length>1)return{index:-1,requested,candidates:scored.filter(x=>x.score===scored[0].score),method:'ambiguous'}}return{index:-1,requested,candidates:[]}}
function resolveDimension(headers,r){return resolve(headers,r,{role:'dimension'})} function resolveMeasure(headers,r){const exact=resolve(headers,r);if(exact.index>=0||exact.candidates.length>1)return exact;const n=normalize(r),role=/revenue/.test(n)?'revenue':/sales/.test(n)?'sales':/cost/.test(n)?'cost':/price/.test(n)?'price':/rating|score/.test(n)?'rating':/quantity|qty|units/.test(n)?'quantity':null;return resolve(headers,r,role?{role}:{} )}
window.InsightFlowSchemaIntelligence={normalize,singular,compact,roles,resolve,resolveDimension,resolveMeasure};
})();